### ISSUE TITLE
Invalid content /en/virtual-machines/kevm/getting-started/mallet-end-to-end/

### ISSUE THREAD

**Issue by facutk** [cardano-foundation/testnets-cardano-org#488]
**Where does the issue occur?**
Expected:
![image](https://user-images.githubusercontent.com/595675/108789507-2ba98080-7559-11eb-9467-4a39867d8e48.png)
Actual:
![image](https://user-images.githubusercontent.com/595675/108789571-4f6cc680-7559-11eb-9398-667a81e4f483.png)

**Describe the issue**
Getting started does not work

- Correct python and node version
![image](https://user-images.githubusercontent.com/595675/108789770-c1dda680-7559-11eb-98d1-a4028a913797.png)
- Docker installed and running
- Contract compiled successfully
```
608060405234801561001057600080fd5b50610139806100206000396000f3fe60806040526004361061003b576000357c010000000000000000000000000000000000000000000000000000000090048063c605f76c14610040575b600080fd5b34801561004c57600080fd5b506100556100d0565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561009557808201518184015260208101905061007a565b50505050905090810190601f1680156100c25780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b60606040805190810160405280600d81526020017f48656c6c6f2c20576f726c64210000000000000000000000000000000000000081525090509056fea165627a7a72305820acfffe6f542426974ff20d01d059db6fbbb31ccc222a11835d16bc517b6b01570029
```

- Test account with funds
- 
![image](https://user-images.githubusercontent.com/595675/108789803-d883fd80-7559-11eb-9182-031f8ee27240.png)

**Expected changes**
Should return Hello World, but returns empty string
```sh
web3.toAscii(web3.eth.call({to: myContractAddress, data: '0xc605f76c'}))
```

**Comment by testacode** [comment]
![image](https://user-images.githubusercontent.com/1852080/108920828-1cd3d400-7614-11eb-88a1-32b2e7e3d85c.png)
same here

**Comment by vadrian** [comment]
Same thing over here.

**Comment by yubi420** [comment]
Two weeks later. Same issue.

**Comment by HennyH** [comment]
I cannot find the block number or transaction hash found in @testacode's answer on the KEVM devnet explorer https://explorer-kevm.portal.dev.cardano.org, presumably it should be there correct?

**Comment by testacode** [comment]
I'm starting to think on cardano as a shitcoin...

**Comment by cleisthenes-alpha** [comment]
I've been able to replicate this issue and have found what seems to work as a fix on my end; full disclosure, I don't know enough about Solidity to know why this is the case.

First, note that all the network-side stuff in Mallet seems to be working fine, so it appears to be an issue with the underlying Solidity code. After some putzing around, I've found the following tweak produces the expected output:
`function helloWorld() **public** pure returns (string memory){`

rather than the code from the tutorial which provides
`function helloWorld() **external** pure returns (string memory){`

Can you test this out and see if it helps? I'm not sure exactly what the repercussions of this minor tweak are, but take a [look at this](https://ethereum.stackexchange.com/questions/19380/external-vs-public-best-practices) for more info on public v. external calls.

**Comment by facutk** [comment]
Hello @cleisthenes-alpha!

Thanks for taking your time on this.

I followed your advice. Updated the contract, compiled it again
![photo_2021-03-10 16 55 33](https://user-images.githubusercontent.com/595675/110689509-867de180-81c1-11eb-8670-c6e2982e230e.jpeg)

Then deployed it again, and called it. 
![photo_2021-03-10 16 55 37](https://user-images.githubusercontent.com/595675/110689534-8da4ef80-81c1-11eb-9e99-6ba7f8c4452d.jpeg)

The same issue again

**Comment by cleisthenes-alpha** [comment]
I'm noticing your call to set myContract is missing the "0x" prefix in this newest iteration. I don't know what the consequences of that are; can you double-check that?

**Comment by facutk** [comment]
![image](https://user-images.githubusercontent.com/595675/110690591-e1640880-81c2-11eb-927c-a0718f127328.png)

tx: https://explorer-kevm.portal.dev.cardano.org/transaction/0xa8b9f74cab2557cd3e538d6d4d6c508f44da28c3bc3f63e6897b3d113f7df698

contract: https://explorer-kevm.portal.dev.cardano.org/account/0x1ADEC841580bCAbcD21307964462c9F05b75206a

**Comment by cleisthenes-alpha** [comment]
I'm mostly out of ideas at this point, as I'm not perfectly replicating your setup (again, playing with Solidity proper in Remix). My last idea: the documentation on [this page for mallet](https://github.com/input-output-hk/mallet/blob/master/docs/mallet_end_to_end_tutorial.org) is almost beat-for-beat what is posted in the KEVM docs, but with the last call different:
`sendTransaction({to: myContractAddress,gas:10000,arguments: []})`
 rather than
`web3.toAscii(web3.eth.call({to: myContractAddress, data: '0xc605f76c'}))`
This is the last idea I've got, so if that doesn't work, I'm sorry I can't be more helpful. Frustrating that something relatively simple in a starter tutorial like this isn't working for many.

**Comment by facutk** [comment]
Thanks a lot for your input cleisthenes-alpha. We still could not make it work.
Maybe the kevm can only interpret some very specific solidity binary.

I've also run out of ideas.

Hopefully someone can go through the starter tutorial and make it work, and fix it so everyone can start testing this.

**Comment by cleisthenes-alpha** [comment]
Alright, I took some time to really dig into this. I've recreated the setup in the tutorial and have run into the exact same problem as you all. I have attempted the following:

- Using 'public' instead of 'external' in the contract function
- Using Solidity 0.8.0 in both the contract and in the compile step to match the video demonstration [here](https://youtu.be/T-4ECqHNjQI?t=2331)
- Attempting to provide a `Function: 'helloWorld()'` or `func: 'helloWorld()'` to sendTransaction, web3.eth.call, iele.callContract, AND iele.constantCall in every permutation I can think of, per [Mallet documentation](https://github.com/input-output-hk/mallet)
- Attempting to manually extract returnData from getRequest()

No progress whatsoever. I've also noticed about four separate sets of conflicting documentation for simple interaction with the KEVM/IELE devnet, all of which feels very roughshod in compilation.

Would love someone else to take a look at this, I've genuinely given it everything I can possibly think of

**Comment by facutk** [comment]
Here is the commit where the KEVM docs were updated. https://github.com/cardano-foundation/testnets-cardano-org/pull/379/commits/613988f2598789d0a588b7c8f77f44fe2b75a77a

`git blame` shows https://github.com/fsancheziohk

Maybe we can reach out to him?

**Comment by facutk** [comment]
The PR was merged by https://github.com/jonnysmillie

https://www.jonnysmillie.co.uk/
hello@jonnysmillie.co.uk

Maybe he has any context whatsoever?

**Comment by SL13PNIR** [comment]
@gmanroney @elviejo79 Do either of you guys know who is responsible for the kevm testnet? Any chance the community could get some assistance please?

**Comment by yubi420** [comment]
Guys, i asked them to make a video demostrating this hello world example and he said there are problems with rpc calls at the moment. They are looking into it. 

(I didnt really want a video about this hello world example but wanted it to be fixed)

**Comment by cleisthenes-alpha** [comment]
Yes, it appears they're recognizing there's a problem and working to solve it. See this commit comment; they're going to remove the Hello World tutorial for now until it's fixed.

https://github.com/cardano-foundation/testnets-cardano-org/commit/ad762daafecf50ac9534c6fb2dee24f711cd46e9#diff-73fc8ad49869b0b7235fc30466f275d0b6428a4850a6ad6f1de348ea265eec6c

**Comment by avilsmeier** [comment]
Hi guys, I was helping Facu troubleshoot this last night but I was able to run the "Hello world" without issues.
I used Chrome's web cache to pull up the old version of the website, these are my steps and environment.

Ubuntu 18
topo-test:~/src/mallet$ nvm --version
0.37.2
topo-test:~/src/mallet$ npm --version
6.9.0
topo-test:~/src/mallet$ node --version
v10.16.3
python -V
Python 2.7.18

Contract address:  0xc00db93ebf8d41b1b6245bc9163315d4703d251b
Account address: 0x08007446d66f54ed8e76cc6e9a9ce7168b4ce94e

I installed everything according to the steps here: 
https://developers.cardano.org/en/virtual-machines/kevm/getting-started/mallet-end-to-end/

And then used these steps for the SC in "Create A HelloWorld Smart Contract".
https://webcache.googleusercontent.com/search?q=cache:YMGZ9pP2mIgJ:https://developers.cardano.org/en/virtual-machines/evm/getting-started/mallet-end-to-end/+&cd=18&hl=es-419&ct=clnk&gl=ar

myAccount = newAccount()
selectAccount(myAccount)
requestFunds()
getBalance()

fs = require("fs");
myContract = "0x" + fs.readFileSync('HelloWorld.bin', 'utf8');
tx = { gas: 470000, data: myContract}
deploymentHash = sendTransaction(tx)

getReceipt(deploymentHash)
myContractAddress = getReceipt(deploymentHash).contractAddress
web3.toAscii(web3.eth.call({to: myContractAddress, data: '0xc605f76c'}))

![image](https://user-images.githubusercontent.com/8103529/111038062-cfbe7300-8405-11eb-9f83-345817a54564.png)

When querying Facu's contract however I also got ' ' as response. If he queries mine he also receives ' ';

Thank you all and have a good one!

**Comment by facutk** [comment]
@avilsmeier gave me a huge hand debugging it from his end.

I tried a different approach and called the RPC directly from Python

https://colab.research.google.com/drive/11fA1WE_GPlVh4_TlAON8Dj9qqjYEHju7#scrollTo=2FdfNYXQBOqt

And the result is working fine

![image](https://user-images.githubusercontent.com/595675/111038638-e4e8d100-8408-11eb-9eec-c8dc9e32dbb0.png)

**Comment by facutk** [comment]
One thing to mention, is that it only works on the EVM network, *not* the KEVM.

![image](https://user-images.githubusercontent.com/595675/111039063-dac7d200-840a-11eb-85dd-cf52c346355a.png)

Where it says
```
./mallet kevm -d ./data
```

It should say
```
./mallet evm -d ./data
```

EVM works as expected
![image](https://user-images.githubusercontent.com/595675/111039086-00ed7200-840b-11eb-8073-91faab7664e8.png)

**Comment by danielrodd** [comment]
That's it! I'm moving to Algorand
